# .pages.yaml

# Media configuration: Defines where images and other assets are stored and how they are referenced.
media:
  input: static/images # Repository path for media files
  output: /images      # URL path prefix for media in content (Hugo specific)
  path: ""             # Optional: Default subfolder in media browser (e.g., "projects")
  extensions: [png, jpg, jpeg, webp, gif, svg] # Allowed file extensions

# Content definitions: Specifies editable content types (collections or single files).
content:
  # "Projects" Collection
  - name: projects
    label: Projects
    path: content/projects # Directory for project markdown files
    type: collection
    format: yaml-frontmatter # YAML frontmatter + Markdown content
    filename: '{year}-{month}-{day}-{primary}.md' # Naming pattern for new project files
    view: # How this collection is displayed in Pages CMS
      primary: title # Main identifying field
      fields: [title, date, draft] # Fields in list view
      sort: [date, title] # Sortable fields
      default: {sort: date, order: desc} # Default sort
    fields: # Frontmatter fields for each project
      - name: title
        label: Title
        type: text
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: image
        label: Project Image
        type: image
        description: "Select from media library. Path will be like /images/projects/your-image.png"
      - name: description
        label: Description
        type: text
      - name: badges
        label: Badges / Technologies Used
        type: string
        list: true
      - name: links # List of link objects
        label: Associated Links
        list: true
        component: link_item # Each item in this list uses the 'link_item' component structure

  # "Tools" Collection
  - name: tools
    label: Tools Used
    path: content/tools # Directory for tools markdown files
    type: collection
    format: yaml-frontmatter
    filename: '{primary}.md' # Naming pattern for new tool files (or use date-based)
    view: # How this collection is displayed in Pages CMS
      primary: title
      fields: [title, date, draft]
      sort: [title, date]
      default: {sort: title, order: asc}
    fields: # Frontmatter fields for each tool
      - name: title
        label: Tool Name
        type: text
        required: true
      - name: date
        label: Date Added / Last Updated
        type: date
        required: true # Assuming tools are treated like dated entries
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: icon
        label: Tool Icon
        type: image
        description: "Optional: Visual icon for the tool (e.g., /images/tools/tool-logo.svg)"
      - name: description
        label: Short Description
        type: text
      # Main content ('body') for tools is implicitly handled by the main editor.

# Components: Reusable groups of fields.
components:
  link_item: # Component for a single link structure
    label: Link Item
    fields:
      - name: icon
        label: Icon Class
        type: string
        description: "FontAwesome icon class (e.g., fab fa-github, fas fa-link)"
      - name: url
        label: URL
        type: string
        required: true
